### ISSUE TITLE
bug/or no-bug

### ISSUE THREAD

**Issue by gusliweb** [rafaelkallis/ticket-tagger#155]
Error when sending mail on my gmail account #5607
 Closed
JunkyardCat opened this issue 6 days ago · 1 comment
 Closed
Error when sending mail on my gmail account
#5607
JunkyardCat opened this issue 6 days ago · 1 comment
Comments
@JunkyardCat
 
JunkyardCat commented 6 days ago
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

If you are unsure whether or not you have found a bug please post to the support forum instead: https://forum.k9mail.app

Describe the bug
error when sending email in gmail

To Reproduce

compose message
write subject: Test
write email:
error in notification bar
Failed to send some messages
Application-specific password required. Learn more at https://support.google.com/mail/?p=invalidsecondfactor
Expected behavior
send email without error

Screenshots

Environment (please complete the following information):

K-9 Mail version: 5.802
Android version: 6.0.1
Device: J7 Prime
Account type: IMAP enabled
Additional context

Logs
Please take some time to retrieve logs and attach them here:

@JunkyardCat JunkyardCat added the bug label 6 days ago
@cketti
 
Member
cketti commented 6 days ago
The error message is from Gmail and it's telling you exactly what the problem is: Application-specific password required.

See https://support.google.com/mail/answer/185833?hl=en

@cketti cketti closed this 6 days ago

**Comment by rafaelkallis** [comment]
Hi @gusliweb hope you like tickettagger! You can easily enable it for your repos (for free!) by using https://github.com/apps/ticket-tagger/installations
