### ISSUE TITLE
Ticket-tagger has stopped labeling issues for the last 10 days or so.

### ISSUE THREAD

**Issue by Zimmi48** [rafaelkallis/ticket-tagger#25]
See https://github.com/coq/bot/issues. The last three issues, from Nov 16th, 18th and 25th (today) were not labeled (the last one was labeled manually by myself). The issues older than that (up to Oct 26th) were labeled automatically by ticket-tagger. As far as I can tell, nothing has been changed in terms of configuration of the GitHub App.

**Comment by rafaelkallis** [comment]
Thank you for reporting. I have identified the cause and a fix is on its way!

**Comment by rafaelkallis** [comment]
As you can see, fixed!

**Comment by Zimmi48** [comment]
Thanks !
